### PR TITLE
Sounds and stuff, not done yet

### PR DESCRIPTION
**Pull request by StrawberyCrepeCookie**
Don't merge yet.

Everything is working except for line 205 in sandbox. I've tried a bunch but it wont work.
If anyone could figure it out then I'd appreciate that.

### CODE REVIEW

**Comment by sm3232** [comment]
The reason 205 isn't working for you is because `playback_callback` is declared as a member function of sandbox. There is no way for miniaudio to access the sandbox object, so it can't call the callback.

An example of this is on line 42, where we have the unordered map for the buttons, you can see that the key for the map is a `Button`, but the value is something weird. `void(Sandbox::*)(void)` is saying "this is a `pointer` to a (`function` that belongs to a `sandbox`) that returns `void` and can take the arguments `void`. (a function taking the arguments `void` is just a function that takes no arguments) Then, when we want to call that sandbox function on line 261, we say `(*this.*(i->second))();`

Miniaudio isn't designed to work with our sandbox struct, so you need to give it either a static function, or a non-member function. 
I would usually just say to go with the static function, but I think that will cause some linking/compiling issues with the `miniaudio.h` file. You're welcome to try it, you would just change line 205 to be `whatever = &Sandbox::playback_callback` and change `playback_callback` to a static function. If that doesn't work, move the `#include "miniaudio.h" and the two functions to mainwindow.cpp and try it all there.

Also - I don't think you need the `extern "C"` here, and don't forget the `#define MINIAUDIO_IMPLEMENTATION` before you `#include "miniaudio.h"`

**Comment by StrawberyCrepeCookie** [comment]
Thank you for the help Connor.

Ive run into another issue about an "unresolved external symbol"
image
Here is a screenshot of the errors.

**Comment by StrawberyCrepeCookie** [comment]
I added everything for sounds to mainwindow.cpp but I'm still getting the unresolved external symbol error
The output is long, but heres the whole message

>------ Build started: Project: CMakeLists, Configuration: Debug ------
  [1/5] Automatic MOC and UIC for target PhysicsSimulator
  [2/5] Building CXX object CMakeFiles\PhysicsSimulator.dir\PhysicsSimulator_autogen\mocs_compilation.cpp.obj
  [3/5] Building CXX object CMakeFiles\PhysicsSimulator.dir\application\main.cpp.obj
  [4/5] Building CXX object CMakeFiles\PhysicsSimulator.dir\application\mainwindow.cpp.obj
  [5/5] Linking CXX executable PhysicsSimulator.exe
  FAILED: PhysicsSimulator.exe 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\PhysicsSimulator.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\link.exe /nologo CMakeFiles\PhysicsSimulator.dir\PhysicsSimulator_autogen\mocs_compilation.cpp.obj CMakeFiles\PhysicsSimulator.dir\application\main.cpp.obj CMakeFiles\PhysicsSimulator.dir\application\mainwindow.cpp.obj  /out:PhysicsSimulator.exe /implib:PhysicsSimulator.lib /pdb:PhysicsSimulator.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:windows  C:\Qt\6.6.2\msvc2019_64\lib\Qt6Widgetsd.lib  C:\Qt\6.6.2\msvc2019_64\lib\Qt6Guid.lib  C:\Qt\6.6.2\msvc2019_64\lib\Qt6Cored.lib  mpr.lib  userenv.lib  C:\Qt\6.6.2\msvc2019_64\lib\Qt6EntryPointd.lib  shell32.lib  d3d11.lib  dxgi.lib  dxguid.lib  d3d12.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
  LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\link.exe /nologo CMakeFiles\PhysicsSimulator.dir\PhysicsSimulator_autogen\mocs_compilation.cpp.obj CMakeFiles\PhysicsSimulator.dir\application\main.cpp.obj CMakeFiles\PhysicsSimulator.dir\application\mainwindow.cpp.obj /out:PhysicsSimulator.exe /implib:PhysicsSimulator.lib /pdb:PhysicsSimulator.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:windows C:\Qt\6.6.2\msvc2019_64\lib\Qt6Widgetsd.lib C:\Qt\6.6.2\msvc2019_64\lib\Qt6Guid.lib C:\Qt\6.6.2\msvc2019_64\lib\Qt6Cored.lib mpr.lib userenv.lib C:\Qt\6.6.2\msvc2019_64\lib\Qt6EntryPointd.lib shell32.lib d3d11.lib dxgi.lib dxguid.lib d3d12.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\PhysicsSimulator.dir/intermediate.manifest CMakeFiles\PhysicsSimulator.dir/manifest.res" failed (exit code 1120) with the following output:
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_get_bytes_per_sample referenced in function ma_get_bytes_per_frame
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_device_config_init referenced in function "bool __cdecl playSound(char const *)" (?playSound@@YA_NPEBD@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_device_init referenced in function "bool __cdecl playSound(char const *)" (?playSound@@YA_NPEBD@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_device_uninit referenced in function "bool __cdecl playSound(char const *)" (?playSound@@YA_NPEBD@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_device_start referenced in function "bool __cdecl playSound(char const *)" (?playSound@@YA_NPEBD@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_device_stop referenced in function "void __cdecl playback_callback(struct ma_device *,void *,void const *,unsigned int)" (?playback_callback@@YAXPEAUma_device@@PEAXPEBXI@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_decoder_init_file referenced in function "bool __cdecl playSound(char const *)" (?playSound@@YA_NPEBD@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_decoder_uninit referenced in function "bool __cdecl playSound(char const *)" (?playSound@@YA_NPEBD@Z)
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\mainwindow.cpp.obj : error LNK2019: unresolved external symbol ma_decoder_read_pcm_frames referenced in function "void __cdecl playback_callback(struct ma_device *,void *,void const *,unsigned int)" (?playback_callback@@YAXPEAUma_device@@PEAXPEBXI@Z)
  
C:\Users\hlabr\Source\Repos\PhysicsSimulator\out\build\PhysicsSimulator.exe : fatal error LNK1120: 9 unresolved externals
  
  ninja: build stopped: subcommand failed.

**Comment by sm3232** [comment]
I think you forgot to include the library in `mainwindow.cpp` (unless it's just not in the commit?)
```C++
#define MINIAUDIO_IMPLEMENTATION
#include "../lib/miniaudio.h"
```
or something like that
(typing this on my phone, might not be the exact spelling and stuff so double check it)

**Pull request closed without merging**
